import assert from "node:assert/strict";
import { hashPassword,verifyPassword,passwordErrors } from "../src/security.js";
const hash=await hashPassword("StrongPass9");
assert.match(hash,/^pbkdf2\$100000\$/);
assert.equal(await verifyPassword("StrongPass9",hash),true);
assert.equal(await verifyPassword("WrongPass9",hash),false);
assert.equal(await verifyPassword("StrongPass9",hash.replace("$100000$","$310000$")),false);
assert.ok(passwordErrors("short").length>0);
assert.ok(passwordErrors("A".repeat(129)+"a1").some(x=>x.includes("128")));
console.log("TEST PASS: password hashing/verification and Worker iteration cap");
