import { readFileSync, existsSync, readdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
const fail=m=>{console.error("AUDIT FAIL:",m);process.exit(1)};
const pkg=JSON.parse(readFileSync("package.json","utf8"));
if(pkg.version!=="5.0.0")fail("package version is not 5.0.0");
for(const f of ["src/index.js","src/db.js","src/security.js","src/routes-auth.js","public/app.js","wrangler.jsonc"])if(!existsSync(f))fail(`missing ${f}`);
const security=readFileSync("src/security.js","utf8");
if(security.includes("310000"))fail("unsupported PBKDF2 iteration count 310000 is still present");
if(!security.includes("ITER=100000"))fail("PBKDF2 must use Cloudflare-compatible 100000 iterations");
const auth=readFileSync("src/routes-auth.js","utf8");
if(!auth.includes('method="post" action="/setup"'))fail("setup form must explicitly POST to /setup");
if(auth.includes("event.preventDefault")||auth.includes('fetch("/setup"'))fail("setup must use a native form, not JS interception");
const client=readFileSync("public/app.js","utf8");
if(client.includes("data-setup-form"))fail("client JS must not intercept setup submission");
const db=readFileSync("src/db.js","utf8");
if(db.includes('VIEWER:["dashboard.view","students.view","students.search","batches.view","lecturers.view","subjects.view","groups.view","reports.view"]'))fail("Viewer must not receive reports by default");
for(const f of readdirSync("src").filter(x=>x.endsWith(".js")))execFileSync(process.execPath,["--check",`src/${f}`],{stdio:"inherit"});
execFileSync(process.execPath,["--check","public/app.js"],{stdio:"inherit"});
console.log("AUDIT PASS: structure, syntax, setup flow guards, Cloudflare crypto guard, Viewer defaults");
