import { can,csrfToken,randomToken,sha256,nowIso } from "./security.js";
import { one,all,run } from "./db.js";
import { esc,authPage,layout,alert } from "./ui.js";
export function render(c,title,body){return c.html(layout({title,org:c.get("org"),user:c.get("user"),currentPath:new URL(c.req.url).pathname,can:p=>can(c,p),csrf:csrfToken(c),body}))}
export function errorPage(c,code,title,message){const u=c.get("user"),o=c.get("org");if(!u)return c.html(authPage({title,org:o,content:`<div class="solo-icon"><i class="fi fi-rr-shield-exclamation"></i></div><h1>${esc(title)}</h1><p class="muted">${esc(message)}</p><a class="btn primary full" href="/login">Go to Login</a>`}),code);return c.html(layout({title,org:o,user:u,currentPath:new URL(c.req.url).pathname,can:p=>can(c,p),csrf:csrfToken(c),body:`<section class="error-card"><strong>${code}</strong><i class="fi fi-rr-shield-exclamation"></i><h1>${esc(title)}</h1><p>${esc(message)}</p><a class="btn primary" href="/dashboard">Back to Dashboard</a></section>`}),code)}
export function requireUser(c){return c.get("user")?null:c.redirect("/login")}
export function requirePerm(c,p){if(!c.get("user"))return c.redirect("/login");return can(c,p)?null:errorPage(c,403,"Access denied","You do not have permission to perform this action.")}
export const cleanEmail=v=>String(v||"").trim().toLowerCase();export const validEmail=v=>/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(String(v||""));
export async function userCount(db){const x=await one(db,"SELECT COUNT(*) AS c FROM users");return Number(x?.c||0)}
export async function makeResetToken(db,userId){const raw=randomToken(),hash=await sha256(raw),expires=new Date(Date.now()+1800000).toISOString();await run(db,"INSERT INTO password_reset_tokens(user_id,token_hash,expires_at,created_at) VALUES (?,?,?,?)",[userId,hash,expires,nowIso()]);return raw}
export async function sendResetEmail(env,to,url){if(!env?.RESEND_API_KEY||!env?.MAIL_FROM)return false;const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${env.RESEND_API_KEY}`},body:JSON.stringify({from:env.MAIL_FROM,to:[to],subject:"Reset your password",html:`<p>A password reset was requested for your Student IMS account.</p><p><a href="${url}">Reset password</a></p><p>This link expires and can only be used once.</p>`})});return r.ok}
export async function lookups(db){return {batches:await all(db,"SELECT * FROM batches WHERE status='ACTIVE' ORDER BY name"),lecturers:await all(db,"SELECT * FROM lecturers WHERE status='ACTIVE' ORDER BY full_name"),subjects:await all(db,"SELECT * FROM subjects WHERE status='ACTIVE' ORDER BY name"),groups:await all(db,"SELECT g.*,b.name AS batch_name FROM groups_table g LEFT JOIN batches b ON b.id=g.batch_id WHERE g.status='ACTIVE' ORDER BY g.name")}}
export async function studentById(db,id){return one(db,`SELECT s.*,b.name AS batch_name,l.full_name AS lecturer_name,sub.name AS subject_name,g.name AS group_name FROM students s LEFT JOIN batches b ON b.id=s.batch_id LEFT JOIN lecturers l ON l.id=s.lecturer_id LEFT JOIN subjects sub ON sub.id=s.subject_id LEFT JOIN groups_table g ON g.id=s.group_id WHERE s.id=?`,[id])}
export function studentForm(csrf,s,refs,error=""){const opt=(rows,k,l,v)=>rows.map(x=>`<option value="${esc(x[k])}" ${String(v||"")===String(x[k])?"selected":""}>${esc(x[l])}</option>`).join("");return `${alert("error",error)}<section class="card form-card"><form method="post" class="grid two"><input type="hidden" name="_csrf" value="${esc(csrf)}"><label><span>Full Name *</span><input name="full_name" required value="${esc(s?.full_name||"")}"></label><label><span>Student Code</span><input name="student_code" value="${esc(s?.student_code||"")}"></label><label><span>Email</span><input type="email" name="email" value="${esc(s?.email||"")}"></label><label><span>Phone</span><input name="phone" value="${esc(s?.phone||"")}"></label><label><span>Batch</span><select name="batch_id"><option value="">Not assigned</option>${opt(refs.batches,"id","name",s?.batch_id)}</select></label><label><span>Lecturer</span><select name="lecturer_id"><option value="">Not assigned</option>${opt(refs.lecturers,"id","full_name",s?.lecturer_id)}</select></label><label><span>Subject</span><select name="subject_id"><option value="">Not assigned</option>${opt(refs.subjects,"id","name",s?.subject_id)}</select></label><label><span>Group</span><select name="group_id"><option value="">Not assigned</option>${opt(refs.groups,"id","name",s?.group_id)}</select></label><label><span>Status</span><select name="status"><option value="ACTIVE" ${s?.status!=="INACTIVE"?"selected":""}>Active</option><option value="INACTIVE" ${s?.status==="INACTIVE"?"selected":""}>Inactive</option></select></label><label class="span2"><span>Notes</span><textarea name="notes" rows="4">${esc(s?.notes||"")}</textarea></label><div class="form-actions span2"><a class="btn ghost" href="/students">Cancel</a><button class="btn primary"><i class="fi fi-rr-disk"></i>Save Student</button></div></form></section>`}
export function parseCsv(text){const rows=[];let row=[],field="",quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(quoted){if(ch==='"'&&next==='"'){field+='"';i++}else if(ch==='"')quoted=false;else field+=ch}else{if(ch==='"')quoted=true;else if(ch===","){row.push(field);field=""}else if(ch==="\n"){row.push(field.replace(/\r$/,"") );rows.push(row);row=[];field=""}else field+=ch}}if(field||row.length){row.push(field.replace(/\r$/,"") );rows.push(row)}if(!rows.length)return[];const h=rows[0].map(x=>x.trim());return rows.slice(1).filter(r=>r.some(x=>String(x).trim())).map(r=>Object.fromEntries(h.map((k,i)=>[k,String(r[i]??"").trim()]))) }
export const csvEscape=v=>`"${String(v??"").replaceAll('"','""')}"`;
