import { Hono } from "hono";
import { dbFor,ensureSchema,one } from "./db.js";
import { loadSession,csrfToken } from "./security.js";
import { esc } from "./ui.js";
import { userCount,errorPage } from "./helpers.js";
import { authRoutes } from "./routes-auth.js";
import { studentRoutes } from "./routes-students.js";
import { academicRoutes } from "./routes-academic.js";
import { adminRoutes } from "./routes-admin.js";
import { systemRoutes } from "./routes-system.js";
const app=new Hono();
const VERSION="6.0.0";
app.use("*",async(c,next)=>{await next();c.header("X-App-Version",VERSION);c.header("X-Content-Type-Options","nosniff");c.header("X-Frame-Options","DENY");c.header("Referrer-Policy","same-origin");c.header("Permissions-Policy","camera=(), microphone=(), geolocation=()");c.header("Content-Security-Policy","default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://cdn-uicons.flaticon.com; font-src https://cdn-uicons.flaticon.com data:; img-src 'self' https: data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");const ct=c.res.headers.get("content-type")||"";if(ct.includes("text/html"))c.header("Cache-Control","no-store, max-age=0");});
app.use("*",async(c,next)=>{try{await ensureSchema(c.env);const db=dbFor(c.env);c.set("db",db);await loadSession(c);c.set("org",await one(db,"SELECT * FROM organizations WHERE id=1"));csrfToken(c);await next()}catch(e){console.error(e);return c.html(`<h1>Startup error</h1><p>${esc(e.message)}</p>`,500)}});
app.get("/health",c=>c.json({ok:true,platform:"cloudflare-workers",version:VERSION}));
app.get("/version",c=>c.json({version:VERSION}));
app.get("/",async c=>{if(await userCount(c.get("db"))===0)return c.redirect("/setup");return c.redirect(c.get("user")?"/dashboard":"/login")});
app.route("/",authRoutes);app.route("/",systemRoutes);app.route("/",studentRoutes);app.route("/",academicRoutes);app.route("/",adminRoutes);
app.notFound(c=>errorPage(c,404,"Page not found","The page you requested could not be found."));
app.onError((e,c)=>{console.error(e);return errorPage(c,e.status||500,e.status===403?"Security check failed":"Something went wrong",e.status===403?e.message:"The server could not complete the request.")});
export default app;
