import { Hono } from "hono";
import { one,run,batch } from "./db.js";
import { nowIso,passwordErrors,hashPassword,verifyPassword,sha256,csrfToken,formBody,audit,createSession,revokeCurrentSession,isLoginLocked,recordLogin,getClientIp } from "./security.js";
import { esc,authPage,alert } from "./ui.js";
import { cleanEmail,validEmail,userCount,errorPage,makeResetToken,sendResetEmail,requireUser } from "./helpers.js";

export const authRoutes=new Hono();
function renderSetup(c,error="",v={}){const content=`<div class="brand-auth"><i class="fi fi-rr-user-crown"></i><div><strong>First System Setup</strong><small>One-time configuration · V6.0.4</small></div></div><span class="kicker">CREATE OWNER</span><h1>Create Owner Account</h1><p class="muted">The first account automatically receives full Owner access. No default credentials are created.</p>${alert("error",error)}<form method="post" action="/setup" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" class="grid two"><input type="hidden" name="_csrf" value="${esc(csrfToken(c))}"><label><span>Full Name *</span><input id="setup_full_name" name="full_name" maxlength="120" autocomplete="name" required value="${esc(v.full_name||"")}"></label><label><span>Phone</span><input id="setup_phone" name="phone" maxlength="40" autocomplete="tel" value="${esc(v.phone||"")}"></label><label class="span2"><span>Email Address *</span><input id="setup_email" type="email" name="email" maxlength="254" autocomplete="email" required value="${esc(v.email||"")}"></label><label><span>Password *</span><input id="setup_password" type="password" name="password" minlength="8" maxlength="128" autocomplete="new-password" required></label><label><span>Confirm Password *</span><input id="setup_confirm_password" type="password" name="confirm_password" minlength="8" maxlength="128" autocomplete="new-password" required></label><p class="hint span2">8–128 characters with uppercase, lowercase and a number.</p><button type="submit" class="btn primary span2">Create Owner & Continue</button></form><div class="setup-version">V6.0.4 · Server-rendered native form</div>`;return c.html(authPage({title:"Create Owner",org:c.get("org"),content}))}
authRoutes.get("/setup",async c=>{if(await userCount(c.get("db"))>0)return c.redirect(c.get("user")?"/dashboard":"/login",303);return renderSetup(c)});
authRoutes.post("/setup",async c=>{const db=c.get("db"),b=await formBody(c),email=cleanEmail(b.email);
if(!String(b.full_name||"").trim()&&!email&&!String(b.password||"")){
  console.warn("Setup POST received empty required values",{contentType:c.req.header("content-type")||""});
}if(await userCount(db)>0)return c.redirect("/login?message="+encodeURIComponent("Owner account already exists. Please sign in."),303);const errors=[];const name=String(b.full_name||"").trim();if(!name)errors.push("Full name is required.");if(name.length>120)errors.push("Full name is too long.");if(!validEmail(email))errors.push("Enter a valid email address.");errors.push(...passwordErrors(String(b.password||"")));if(b.password!==b.confirm_password)errors.push("Passwords do not match.");if(errors.length)return renderSetup(c,errors.join(" "),{full_name:name,phone:b.phone,email});const ts=nowIso(),passwordHash=await hashPassword(String(b.password),c.env?.AUTH_PEPPER||"");const inserted=await run(db,`INSERT INTO users(full_name,email,phone,password_hash,role,status,created_at,updated_at) SELECT ?,?,?,?,'OWNER','ACTIVE',?,? WHERE NOT EXISTS(SELECT 1 FROM users)`,[name,email,String(b.phone||"").trim()||null,passwordHash,ts,ts]);if(!inserted.changes)return c.redirect("/login?message="+encodeURIComponent("Owner account already exists. Please sign in."),303);const owner=await one(db,"SELECT id,email FROM users WHERE email=? LIMIT 1",[email]);if(!owner)return renderSetup(c,"The account was saved but could not be read back. Open Login and sign in with the credentials you entered.",{full_name:name,phone:b.phone,email});try{await audit(c,"user.created","users","user",owner.id,{role:"OWNER",source:"system_setup"},Number(owner.id))}catch(e){console.error("Owner audit failed",e)}return c.redirect("/login?message="+encodeURIComponent("Owner account created successfully. Please sign in."),303)});
authRoutes.get("/login",async c=>{if(await userCount(c.get("db"))===0)return c.redirect("/setup");if(c.get("user"))return c.redirect("/dashboard");const msg=new URL(c.req.url).searchParams.get("message");const content=`<div class="brand-auth"><i class="fi fi-rr-graduation-cap"></i><div><strong>${esc(c.get("org").short_name)}</strong><small>Secure access</small></div></div><span class="kicker">WELCOME BACK</span><h1>Sign in to your account</h1><p class="muted">Enter your credentials to continue.</p>${alert("success",msg)}<form method="post" class="stack"><input type="hidden" name="_csrf" value="${esc(csrfToken(c))}"><label><span>Email Address</span><input type="email" name="email" required autocomplete="email"></label><label><span>Password</span><div class="password"><input id="loginpw" type="password" name="password" required autocomplete="current-password"><button type="button" data-pw="loginpw"><i class="fi fi-rr-eye"></i></button></div></label><div class="form-row"><label class="check"><input type="checkbox" name="remember"><span>Remember me</span></label><a href="/forgot-password">Forgot password?</a></div><button class="btn primary full"><i class="fi fi-rr-sign-in-alt"></i>Login</button></form>`;return c.html(authPage({title:"Login",org:c.get("org"),content}))});
authRoutes.post("/login",async c=>{const b=await formBody(c),db=c.get("db"),email=cleanEmail(b.email),address=getClientIp(c);if(await isLoginLocked(db,email,address)){await audit(c,"auth.login.blocked","auth",null,null,{email});return errorPage(c,429,"Too many attempts","Please wait before trying again.")}const user=await one(db,"SELECT * FROM users WHERE email=?",[email]),valid=!!user&&user.status==="ACTIVE"&&await verifyPassword(String(b.password||""),user.password_hash,c.env?.AUTH_PEPPER||"");await recordLogin(c,email,valid);if(!valid){await audit(c,"auth.login.failed","auth","user",user?.id||null,{email});const content=`<h1>Sign in</h1>${alert("error","Invalid email or password.")}<form method="post" class="stack"><input type="hidden" name="_csrf" value="${esc(csrfToken(c))}"><label><span>Email</span><input type="email" name="email" value="${esc(email)}" required></label><label><span>Password</span><input type="password" name="password" required></label><button class="btn primary full">Login</button></form>`;return c.html(authPage({title:"Login",org:c.get("org"),content}),401)}await run(db,"UPDATE users SET last_login_at=?,updated_at=? WHERE id=?",[nowIso(),nowIso(),user.id]);await createSession(c,Number(user.id),b.remember==="on");try{await audit(c,"auth.login.success","auth","user",user.id,null,Number(user.id))}catch(e){console.error("Login audit failed",e)}return c.redirect("/dashboard",303)});
authRoutes.post("/logout",async c=>{if(requireUser(c))return c.redirect("/login");await formBody(c);try{await audit(c,"auth.logout","auth","user",c.get("user").id)}catch(e){console.error("Logout audit failed",e)}await revokeCurrentSession(c);return c.redirect("/login?message="+encodeURIComponent("You have been logged out."),303)});

authRoutes.get("/forgot-password",c=>c.html(authPage({title:"Forgot Password",org:c.get("org"),content:`<a class="back" href="/login">← Back to login</a><div class="solo-icon"><i class="fi fi-rr-key"></i></div><h1>Forgot password?</h1><p class="muted">Enter your email. The response is always generic for security.</p><form method="post" class="stack"><input type="hidden" name="_csrf" value="${esc(csrfToken(c))}"><label><span>Email Address</span><input type="email" name="email" required></label><button class="btn primary full">Send Reset Link</button></form>`})));
authRoutes.post("/forgot-password",async c=>{const b=await formBody(c),db=c.get("db"),email=cleanEmail(b.email),user=await one(db,"SELECT id,email FROM users WHERE email=? AND status='ACTIVE'",[email]);if(user){const raw=await makeResetToken(db,Number(user.id)),url=`${new URL(c.req.url).origin}/reset-password?token=${encodeURIComponent(raw)}`;try{await sendResetEmail(c.env,user.email,url)}catch(e){console.error(e)}await audit(c,"password.reset_requested","auth","user",user.id,null,Number(user.id))}return c.html(authPage({title:"Forgot Password",org:c.get("org"),content:`<div class="solo-icon"><i class="fi fi-rr-envelope"></i></div><h1>Check your email</h1>${alert("success","If an account exists for this email, password reset instructions have been sent.")}<a class="btn primary full" href="/login">Back to Login</a>`}))});
authRoutes.get("/reset-password",c=>{const token=new URL(c.req.url).searchParams.get("token")||"";return c.html(authPage({title:"Reset Password",org:c.get("org"),content:`<div class="solo-icon"><i class="fi fi-rr-password"></i></div><h1>Set a new password</h1><form method="post" class="stack"><input type="hidden" name="_csrf" value="${esc(csrfToken(c))}"><input type="hidden" name="token" value="${esc(token)}"><label><span>New Password</span><input type="password" name="password" required></label><label><span>Confirm Password</span><input type="password" name="confirm_password" required></label><button class="btn primary full">Reset Password</button></form>`}))});
authRoutes.post("/reset-password",async c=>{const b=await formBody(c),db=c.get("db"),errors=passwordErrors(String(b.password||""));if(b.password!==b.confirm_password)errors.push("Passwords do not match.");if(errors.length)return errorPage(c,400,"Password not changed",errors.join(" "));const row=await one(db,"SELECT * FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL",[await sha256(String(b.token||""))]);if(!row||new Date(row.expires_at).getTime()<=Date.now())return errorPage(c,400,"Invalid reset link","This password reset link is invalid or expired.");const ts=nowIso();await batch(db,[{sql:"UPDATE users SET password_hash=?,updated_at=? WHERE id=?",args:[await hashPassword(String(b.password),c.env?.AUTH_PEPPER||""),ts,row.user_id]},{sql:"UPDATE password_reset_tokens SET used_at=? WHERE id=?",args:[ts,row.id]},{sql:"UPDATE sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL",args:[ts,row.user_id]}]);await audit(c,"password.reset_completed","auth","user",row.user_id,null,Number(row.user_id));return c.html(authPage({title:"Password Updated",org:c.get("org"),content:`<div class="solo-icon"><i class="fi fi-rr-check-circle"></i></div><h1>Password updated</h1><p class="muted">You can now sign in with your new password.</p><a class="btn primary full" href="/login">Go to Login</a>`}))});
