import { Hono } from "hono";
import { one,run,batch } from "./db.js";
import { nowIso,passwordErrors,hashPassword,verifyPassword,sha256,csrfToken,formBody,audit,createSession,revokeCurrentSession,isLoginLocked,recordLogin,getClientIp } from "./security.js";
import { esc,authPage,alert } from "./ui.js";
import { cleanEmail,validEmail,userCount,errorPage,makeResetToken,sendResetEmail,requireUser } from "./helpers.js";

export const authRoutes=new Hono();
authRoutes.get("/setup",async c=>{if(await userCount(c.get("db"))>0)return c.redirect(c.get("user")?"/dashboard":"/login");const content=`<div class="brand-auth"><i class="fi fi-rr-user-crown"></i><div><strong>First System Setup</strong><small>One-time configuration</small></div></div><span class="kicker">CREATE OWNER</span><h1>Create Owner Account</h1><p class="muted">The first account automatically receives full Owner access. No default credentials are created.</p><form method="post" class="grid two"><input type="hidden" name="_csrf" value="${esc(csrfToken(c))}"><label><span>Full Name *</span><input name="full_name" required></label><label><span>Phone</span><input name="phone"></label><label class="span2"><span>Email Address *</span><input type="email" name="email" required></label><label><span>Password *</span><input type="password" name="password" required></label><label><span>Confirm Password *</span><input type="password" name="confirm_password" required></label><p class="hint span2">Minimum 8 characters with uppercase, lowercase and a number.</p><button class="btn primary span2">Create Owner & Continue</button></form>`;return c.html(authPage({title:"Create Owner",org:c.get("org"),content}))});
authRoutes.post("/setup",async c=>{const db=c.get("db");if(await userCount(db)>0)return c.redirect("/login");const b=await formBody(c),errors=[];if(!String(b.full_name||"").trim())errors.push("Full name is required.");if(!validEmail(b.email))errors.push("Enter a valid email.");errors.push(...passwordErrors(String(b.password||"")));if(b.password!==b.confirm_password)errors.push("Passwords do not match.");if(errors.length)return errorPage(c,400,"Owner account not created",errors.join(" "));const ts=nowIso(),r=await run(db,`INSERT INTO users(full_name,email,phone,password_hash,role,status,created_at,updated_at) SELECT ?,?,?,?,'OWNER','ACTIVE',?,? WHERE NOT EXISTS(SELECT 1 FROM users)`,[String(b.full_name).trim(),cleanEmail(b.email),String(b.phone||"").trim()||null,await hashPassword(String(b.password)),ts,ts]);if(!r.changes)return c.redirect("/login");await createSession(c,r.lastInsertRowid,false);await audit(c,"user.created","users","user",r.lastInsertRowid,{role:"OWNER",source:"system_setup"},r.lastInsertRowid);return c.redirect("/dashboard")});

authRoutes.get("/login",async c=>{if(await userCount(c.get("db"))===0)return c.redirect("/setup");if(c.get("user"))return c.redirect("/dashboard");const msg=new URL(c.req.url).searchParams.get("message");const content=`<div class="brand-auth"><i class="fi fi-rr-graduation-cap"></i><div><strong>${esc(c.get("org").short_name)}</strong><small>Secure access</small></div></div><span class="kicker">WELCOME BACK</span><h1>Sign in to your account</h1><p class="muted">Enter your credentials to continue.</p>${alert("success",msg)}<form method="post" class="stack"><input type="hidden" name="_csrf" value="${esc(csrfToken(c))}"><label><span>Email Address</span><input type="email" name="email" required autocomplete="email"></label><label><span>Password</span><div class="password"><input id="loginpw" type="password" name="password" required autocomplete="current-password"><button type="button" data-pw="loginpw"><i class="fi fi-rr-eye"></i></button></div></label><div class="form-row"><label class="check"><input type="checkbox" name="remember"><span>Remember me</span></label><a href="/forgot-password">Forgot password?</a></div><button class="btn primary full"><i class="fi fi-rr-sign-in-alt"></i>Login</button></form>`;return c.html(authPage({title:"Login",org:c.get("org"),content}))});
authRoutes.post("/login",async c=>{const b=await formBody(c),db=c.get("db"),email=cleanEmail(b.email),address=getClientIp(c);if(await isLoginLocked(db,email,address)){await audit(c,"auth.login.blocked","auth",null,null,{email});return errorPage(c,429,"Too many attempts","Please wait before trying again.")}const user=await one(db,"SELECT * FROM users WHERE email=?",[email]),valid=!!user&&user.status==="ACTIVE"&&await verifyPassword(String(b.password||""),user.password_hash);await recordLogin(c,email,valid);if(!valid){await audit(c,"auth.login.failed","auth","user",user?.id||null,{email});const content=`<h1>Sign in</h1>${alert("error","Invalid email or password.")}<form method="post" class="stack"><input type="hidden" name="_csrf" value="${esc(csrfToken(c))}"><label><span>Email</span><input type="email" name="email" value="${esc(email)}" required></label><label><span>Password</span><input type="password" name="password" required></label><button class="btn primary full">Login</button></form>`;return c.html(authPage({title:"Login",org:c.get("org"),content}),401)}await run(db,"UPDATE users SET last_login_at=?,updated_at=? WHERE id=?",[nowIso(),nowIso(),user.id]);await createSession(c,Number(user.id),b.remember==="on");await audit(c,"auth.login.success","auth","user",user.id,null,Number(user.id));return c.redirect("/dashboard")});
authRoutes.post("/logout",async c=>{if(requireUser(c))return c.redirect("/login");await formBody(c);await audit(c,"auth.logout","auth","user",c.get("user").id);await revokeCurrentSession(c);return c.redirect("/login?message="+encodeURIComponent("You have been logged out."))});

authRoutes.get("/forgot-password",c=>c.html(authPage({title:"Forgot Password",org:c.get("org"),content:`<a class="back" href="/login">← Back to login</a><div class="solo-icon"><i class="fi fi-rr-key"></i></div><h1>Forgot password?</h1><p class="muted">Enter your email. The response is always generic for security.</p><form method="post" class="stack"><input type="hidden" name="_csrf" value="${esc(csrfToken(c))}"><label><span>Email Address</span><input type="email" name="email" required></label><button class="btn primary full">Send Reset Link</button></form>`})));
authRoutes.post("/forgot-password",async c=>{const b=await formBody(c),db=c.get("db"),email=cleanEmail(b.email),user=await one(db,"SELECT id,email FROM users WHERE email=? AND status='ACTIVE'",[email]);if(user){const raw=await makeResetToken(db,Number(user.id)),url=`${new URL(c.req.url).origin}/reset-password?token=${encodeURIComponent(raw)}`;try{await sendResetEmail(c.env,user.email,url)}catch(e){console.error(e)}await audit(c,"password.reset_requested","auth","user",user.id,null,Number(user.id))}return c.html(authPage({title:"Forgot Password",org:c.get("org"),content:`<div class="solo-icon"><i class="fi fi-rr-envelope"></i></div><h1>Check your email</h1>${alert("success","If an account exists for this email, password reset instructions have been sent.")}<a class="btn primary full" href="/login">Back to Login</a>`}))});
authRoutes.get("/reset-password",c=>{const token=new URL(c.req.url).searchParams.get("token")||"";return c.html(authPage({title:"Reset Password",org:c.get("org"),content:`<div class="solo-icon"><i class="fi fi-rr-password"></i></div><h1>Set a new password</h1><form method="post" class="stack"><input type="hidden" name="_csrf" value="${esc(csrfToken(c))}"><input type="hidden" name="token" value="${esc(token)}"><label><span>New Password</span><input type="password" name="password" required></label><label><span>Confirm Password</span><input type="password" name="confirm_password" required></label><button class="btn primary full">Reset Password</button></form>`}))});
authRoutes.post("/reset-password",async c=>{const b=await formBody(c),db=c.get("db"),errors=passwordErrors(String(b.password||""));if(b.password!==b.confirm_password)errors.push("Passwords do not match.");if(errors.length)return errorPage(c,400,"Password not changed",errors.join(" "));const row=await one(db,"SELECT * FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL",[await sha256(String(b.token||""))]);if(!row||new Date(row.expires_at).getTime()<=Date.now())return errorPage(c,400,"Invalid reset link","This password reset link is invalid or expired.");const ts=nowIso();await batch(db,[{sql:"UPDATE users SET password_hash=?,updated_at=? WHERE id=?",args:[await hashPassword(String(b.password)),ts,row.user_id]},{sql:"UPDATE password_reset_tokens SET used_at=? WHERE id=?",args:[ts,row.id]},{sql:"UPDATE sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL",args:[ts,row.user_id]}]);await audit(c,"password.reset_completed","auth","user",row.user_id,null,Number(row.user_id));return c.html(authPage({title:"Password Updated",org:c.get("org"),content:`<div class="solo-icon"><i class="fi fi-rr-check-circle"></i></div><h1>Password updated</h1><p class="muted">You can now sign in with your new password.</p><a class="btn primary full" href="/login">Go to Login</a>`}))});
