import { getCookie,setCookie,deleteCookie } from "hono/cookie";
import { all,one,run } from "./db.js";
const enc=new TextEncoder(),SESSION="sims_session",CSRF="sims_csrf",ITER=100000,MAX_ITER=100000,MAX_PASSWORD_LENGTH=128;
export const nowIso=()=>new Date().toISOString();
const b64=b=>{let s="";b.forEach(x=>s+=String.fromCharCode(x));return btoa(s)};
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
export function randomToken(n=32){return b64(crypto.getRandomValues(new Uint8Array(n))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
export async function sha256(v){return b64(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(String(v)))))}
export function passwordErrors(p){const e=[];p=String(p||"");if(p.length<8)e.push("Password must be at least 8 characters.");if(p.length>MAX_PASSWORD_LENGTH)e.push("Password must be 128 characters or fewer.");if(!/[A-Z]/.test(p))e.push("Add an uppercase letter.");if(!/[a-z]/.test(p))e.push("Add a lowercase letter.");if(!/[0-9]/.test(p))e.push("Add a number.");return e}
export async function hashPassword(p){const salt=crypto.getRandomValues(new Uint8Array(16)),key=await crypto.subtle.importKey("raw",enc.encode(p),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations:ITER},key,256);return `pbkdf2$${ITER}$${b64(salt)}$${b64(new Uint8Array(bits))}`}
export async function verifyPassword(p,stored){try{const [kind,it,salt64,hash64]=String(stored).split("$");if(kind!=="pbkdf2")return false;const iterations=Number(it);if(!Number.isInteger(iterations)||iterations<1||iterations>MAX_ITER)return false;const salt=unb64(salt64),expected=unb64(hash64),key=await crypto.subtle.importKey("raw",enc.encode(p),"PBKDF2",false,["deriveBits"]),bits=new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations},key,expected.length*8));let d=bits.length===expected.length?0:1;for(let i=0;i<Math.min(bits.length,expected.length);i++)d|=bits[i]^expected[i];return d===0}catch{return false}}
export async function effectivePermissions(db,u){if(!u||u.status!=="ACTIVE")return new Set();if(u.role==="OWNER")return new Set((await all(db,"SELECT key FROM permissions")).map(x=>x.key));const s=new Set((await all(db,"SELECT p.key FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.role=?",[u.role])).map(x=>x.key));for(const r of await all(db,"SELECT p.key,up.allowed FROM user_permissions up JOIN permissions p ON p.id=up.permission_id WHERE up.user_id=?",[u.id]))Number(r.allowed)?s.add(r.key):s.delete(r.key);return s}
export function can(c,p){const u=c.get("user");return !!u&&u.status==="ACTIVE"&&(u.role==="OWNER"||c.get("permissions")?.has(p))}
export function csrfToken(c){let t=getCookie(c,CSRF);if(!t){t=randomToken(24);setCookie(c,CSRF,t,{path:"/",httpOnly:false,secure:new URL(c.req.url).protocol==="https:",sameSite:"Lax",maxAge:86400})}return t}
export async function formBody(c){const b=await c.req.parseBody(),cookie=getCookie(c,CSRF)||"",sent=String(b._csrf||"");if(!cookie||!sent||cookie!==sent){const e=new Error("Security check failed. Refresh and try again.");e.status=403;throw e}return b}
const ip=c=>c.req.header("CF-Connecting-IP")||c.req.header("x-forwarded-for")||"";
export async function audit(c,action,module,targetType=null,targetId=null,metadata=null,uid=null){await run(c.get("db"),"INSERT INTO activity_logs(user_id,action,module,target_type,target_id,metadata,ip_address,user_agent,created_at) VALUES (?,?,?,?,?,?,?,?,?)",[uid??c.get("user")?.id??null,action,module,targetType,targetId==null?null:String(targetId),metadata?JSON.stringify(metadata):null,ip(c),c.req.header("user-agent")||"",nowIso()])}
export async function createSession(c,userId,remember=false){const raw=randomToken(),hash=await sha256(raw),secs=remember?2592000:43200,exp=new Date(Date.now()+secs*1000);await run(c.get("db"),"INSERT INTO sessions(user_id,token_hash,ip_address,user_agent,expires_at,last_activity_at,created_at) VALUES (?,?,?,?,?,?,?)",[userId,hash,ip(c),c.req.header("user-agent")||"",exp.toISOString(),nowIso(),nowIso()]);setCookie(c,SESSION,raw,{path:"/",httpOnly:true,secure:new URL(c.req.url).protocol==="https:",sameSite:"Lax",maxAge:secs})}
export async function revokeCurrentSession(c){const raw=getCookie(c,SESSION);if(raw)await run(c.get("db"),"UPDATE sessions SET revoked_at=? WHERE token_hash=? AND revoked_at IS NULL",[nowIso(),await sha256(raw)]);deleteCookie(c,SESSION,{path:"/"})}
export async function loadSession(c){const raw=getCookie(c,SESSION);if(!raw){c.set("user",null);c.set("permissions",new Set());return}const db=c.get("db"),r=await one(db,"SELECT s.id AS session_id,s.user_id,s.expires_at,s.last_activity_at,u.full_name,u.email,u.phone,u.role,u.status,u.last_login_at,u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL",[await sha256(raw)]);if(!r||r.status!=="ACTIVE"||new Date(r.expires_at).getTime()<=Date.now()){if(r?.session_id)await run(db,"UPDATE sessions SET revoked_at=? WHERE id=?",[nowIso(),r.session_id]);deleteCookie(c,SESSION,{path:"/"});c.set("user",null);c.set("permissions",new Set());return}const u={id:Number(r.user_id),full_name:r.full_name,email:r.email,phone:r.phone,role:r.role,status:r.status,last_login_at:r.last_login_at,created_at:r.created_at};c.set("user",u);c.set("permissions",await effectivePermissions(db,u));c.set("sessionId",Number(r.session_id));if(!r.last_activity_at||Date.now()-new Date(r.last_activity_at).getTime()>300000)await run(db,"UPDATE sessions SET last_activity_at=? WHERE id=?",[nowIso(),r.session_id])}
export async function isLoginLocked(db,email,address){const since=new Date(Date.now()-900000).toISOString(),r=await one(db,"SELECT COUNT(*) AS c FROM login_attempts WHERE success=0 AND created_at>=? AND (email=? OR ip_address=?)",[since,email||"",address||""]);return Number(r?.c||0)>=7}
export async function recordLogin(c,email,success){await run(c.get("db"),"INSERT INTO login_attempts(email,ip_address,success,created_at) VALUES (?,?,?,?)",[email,ip(c),success?1:0,nowIso()])}
export const getClientIp=ip;
