import { esc, msg } from "./utils.js";
import { can } from "./db.js";

export const CSS=`
:root{color-scheme:light;--bg:#f5f7fb;--panel:#fff;--panel-2:#f9fbff;--text:#172033;--muted:#748197;--line:#e5eaf1;--brand:#3668f2;--brand2:#264fc6;--brand-soft:#edf2ff;--danger:#c43b4d;--danger-soft:#fff0f1;--ok:#187250;--ok-soft:#ebf9f2;--input:#fff;--table-head:#fbfcfe;--sidebar:#121a2b;--sidebar-text:#dfe7fa;--sidebar-muted:#91a0ba;--sidebar-hover:#1e2a43;--shadow:0 12px 34px rgba(20,35,60,.07);--shadow-soft:0 5px 18px rgba(25,38,65,.04);--radius:15px;--sidebar-width:244px;--page-pad:24px;--row-pad:11px 12px}
:root[data-theme="dark"]{color-scheme:dark;--bg:#0d111b;--panel:#151b27;--panel-2:#101620;--text:#edf2fb;--muted:#98a5ba;--line:#273144;--brand:#7698ff;--brand2:#9ab2ff;--brand-soft:#202b45;--danger:#ff8a98;--danger-soft:#321b23;--ok:#5bd09d;--ok-soft:#153329;--input:#101620;--table-head:#111722;--sidebar:#0a0f18;--sidebar-text:#e7ecf7;--sidebar-muted:#8996ad;--sidebar-hover:#172033;--shadow:0 16px 38px rgba(0,0,0,.28);--shadow-soft:0 7px 20px rgba(0,0,0,.18)}
*{box-sizing:border-box}html{font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;background:var(--bg);color:var(--text);scroll-behavior:smooth}body{margin:0;background:var(--bg);min-height:100vh;transition:background .18s,color .18s}a{text-decoration:none;color:inherit}button,input,select,textarea{font:inherit}.muted{color:var(--muted)}.small{font-size:12px}.icon-btn{width:38px;height:38px;border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:11px;display:inline-grid;place-items:center;cursor:pointer;transition:.18s ease}.icon-btn:hover{transform:translateY(-1px);border-color:var(--brand);background:var(--brand-soft);color:var(--brand)}.display-controls{display:flex;align-items:center;gap:8px}.control-chip{height:38px;border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:11px;padding:0 11px;display:flex;align-items:center;gap:8px;cursor:pointer;transition:.16s}.control-chip:hover{background:var(--brand-soft);color:var(--brand);border-color:var(--brand)}
.auth{min-height:100vh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 15% 10%,rgba(54,104,242,.14),transparent 38%),var(--bg);position:relative}.auth-tools{position:fixed;right:22px;top:22px;z-index:2}.auth-card{width:min(560px,100%);background:var(--panel);border:1px solid var(--line);border-radius:24px;padding:34px;box-shadow:var(--shadow);transition:background .2s,border-color .2s}.brand{display:flex;gap:12px;align-items:center;margin-bottom:23px}.brand i{font-size:29px;color:var(--brand)}.brand strong{font-size:19px}.brand small{display:block;color:var(--muted);font-size:11px;margin-top:2px}h1{font-size:27px;margin:0 0 8px;letter-spacing:-.025em}h2{font-size:19px;margin:0 0 12px}h3{font-size:15px;margin:0 0 10px}.grid{display:grid;gap:15px}.two{grid-template-columns:repeat(2,minmax(0,1fr))}.span2{grid-column:1/-1}label span{display:block;font-size:12px;font-weight:700;margin-bottom:7px}input,select,textarea{width:100%;border:1px solid var(--line);border-radius:11px;padding:11px 12px;background:var(--input);color:var(--text);outline:none;transition:.16s ease}input::placeholder,textarea::placeholder{color:var(--muted)}textarea{min-height:96px;resize:vertical}input:focus,select:focus,textarea:focus{border-color:var(--brand);box-shadow:0 0 0 3px rgba(54,104,242,.15)}.btn{border:0;border-radius:10px;padding:10px 14px;font-weight:750;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:8px;transition:.16s ease}.btn:hover{transform:translateY(-1px)}.btn.primary{background:var(--brand);color:#fff}.btn.primary:hover{background:var(--brand2)}.btn.soft{background:var(--brand-soft);color:var(--brand)}.btn.danger{background:var(--danger-soft);color:var(--danger);border:1px solid var(--line)}.btn.small{padding:7px 10px;font-size:12px}.notice{padding:11px 13px;border-radius:10px;margin:14px 0;font-size:13px}.notice.error{background:var(--danger-soft);color:var(--danger);border:1px solid var(--line)}.notice.success{background:var(--ok-soft);color:var(--ok);border:1px solid var(--line)}
.app{min-height:100vh;display:grid;grid-template-columns:var(--sidebar-width) minmax(0,1fr);transition:grid-template-columns .22s ease}.sidebar{background:var(--sidebar);color:var(--sidebar-text);padding:18px 13px;position:sticky;top:0;height:100vh;z-index:20;transition:width .22s,transform .22s}.side-brand{display:flex;gap:10px;align-items:center;padding:8px 9px 18px;min-height:58px;overflow:hidden}.side-brand i{font-size:25px;color:#8fb0ff;flex:0 0 auto}.side-brand strong{display:block;white-space:nowrap;max-width:172px;overflow:hidden;text-overflow:ellipsis}.side-brand small{display:block;color:var(--sidebar-muted);font-size:11px;white-space:nowrap}.sidebar-tools{display:flex;justify-content:flex-end;padding:0 4px 10px}.sidebar-collapse{background:transparent;border:1px solid #27334a;color:#aab8d0}.nav{display:grid;gap:4px}.nav a{padding:10px 11px;border-radius:9px;color:#b9c4d9;font-size:13px;display:flex;gap:10px;align-items:center;white-space:nowrap;min-height:40px;transition:.15s}.nav a i{font-size:17px;min-width:18px;text-align:center}.nav a:hover,.nav a.active{background:var(--sidebar-hover);color:#fff}.nav a.active{box-shadow:inset 3px 0 0 #7698ff}.nav .sep{height:1px;background:#24304a;margin:8px 7px}.sidebar-collapsed{--sidebar-width:76px}.sidebar-collapsed .side-brand div,.sidebar-collapsed .nav a span,.sidebar-collapsed .side-brand small{display:none}.sidebar-collapsed .side-brand{justify-content:center}.sidebar-collapsed .nav a{justify-content:center;padding:10px}.sidebar-collapsed .nav a.active{box-shadow:inset 0 0 0 1px #3c527d}.sidebar-collapsed .sidebar-tools{justify-content:center}
.main{min-width:0}.topbar{height:68px;background:var(--panel);border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 var(--page-pad);position:sticky;top:0;z-index:10}.topbar-left,.topbar-right{display:flex;align-items:center;gap:10px}.mobile-menu{display:none}.top-title{font-weight:800;letter-spacing:-.015em}.userchip{display:flex;align-items:center;gap:9px;border-left:1px solid var(--line);padding-left:12px}.avatar{width:36px;height:36px;border-radius:12px;background:var(--brand-soft);color:var(--brand);display:grid;place-items:center;font-weight:800}.page{padding:var(--page-pad);max-width:1500px;width:100%;margin:0 auto}.page-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:20px}.page-head h1{font-size:26px}.actions{display:flex;gap:8px;flex-wrap:wrap}.cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:15px}.card{background:var(--panel);border:1px solid var(--line);border-radius:var(--radius);padding:18px;box-shadow:var(--shadow-soft);transition:.18s ease}.card:hover{transform:translateY(-2px);border-color:var(--brand);box-shadow:var(--shadow)}.stat{display:flex;justify-content:space-between;align-items:flex-start}.stat b{font-size:29px;letter-spacing:-.035em}.stat i{font-size:23px;color:var(--brand);background:var(--brand-soft);padding:10px;border-radius:11px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow-soft);overflow:hidden;margin-bottom:18px}.panel-head{padding:16px 18px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.panel-body{padding:18px}.table-wrap{overflow:auto;max-width:100%}table{width:100%;border-collapse:separate;border-spacing:0;font-size:13px}th,td{text-align:left;padding:var(--row-pad);border-bottom:1px solid var(--line);vertical-align:middle}th{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.05em;background:var(--table-head);position:sticky;top:0;z-index:1}tbody tr{transition:background .12s}tbody tr:hover{background:var(--panel-2)}.badge{display:inline-flex;padding:4px 8px;border-radius:999px;font-size:10px;font-weight:800;background:var(--brand-soft);color:var(--brand)}.badge.ok{background:var(--ok-soft);color:var(--ok)}.badge.off{background:var(--panel-2);color:var(--muted)}.toolbar{display:flex;gap:9px;align-items:end;flex-wrap:wrap}.toolbar label{min-width:150px;flex:1}.toolbar .compact{flex:0 0 auto;min-width:110px}.checks{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.check{display:flex;gap:8px;align-items:flex-start;border:1px solid var(--line);border-radius:10px;padding:10px;background:var(--panel-2)}.check input{width:auto;margin-top:2px}.check span{margin:0;font-weight:600;font-size:12px}.empty{padding:28px;text-align:center;color:var(--muted)}.footer-note{font-size:11px;color:var(--muted);margin-top:16px}.mobile-overlay{display:none}
.density-compact{--page-pad:18px;--row-pad:7px 10px}.density-compact .panel-body{padding:14px}.density-compact .card{padding:14px}.density-compact .topbar{height:60px}.density-compact .nav a{min-height:35px;padding-top:7px;padding-bottom:7px}
@media(max-width:980px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))}.checks{grid-template-columns:1fr 1fr}.control-chip span{display:none}.control-chip{width:38px;padding:0;justify-content:center}}
@media(max-width:820px){.app{grid-template-columns:1fr}.sidebar{position:fixed;left:0;transform:translateX(-105%);width:min(286px,86vw);box-shadow:18px 0 42px rgba(0,0,0,.25)}.sidebar-collapsed{--sidebar-width:244px}.sidebar-collapsed .side-brand div,.sidebar-collapsed .nav a span,.sidebar-collapsed .side-brand small{display:block}.sidebar-collapsed .side-brand{justify-content:flex-start}.sidebar-collapsed .nav a{justify-content:flex-start;padding:10px 11px}.sidebar-tools{display:none}.mobile-nav-open .sidebar{transform:translateX(0)}.mobile-overlay{display:block;position:fixed;inset:0;background:rgba(0,0,0,.38);z-index:19;opacity:0;pointer-events:none;transition:.2s}.mobile-nav-open .mobile-overlay{opacity:1;pointer-events:auto}.mobile-menu{display:inline-grid}.topbar{padding:0 16px}.page{padding:18px}.top-title{display:none}.userchip>div:last-child{display:none}.userchip{padding-left:8px}}
@media(max-width:600px){.two,.cards,.checks{grid-template-columns:1fr}.span2{grid-column:auto}.page{padding:14px}.auth-card{padding:24px 20px}.page-head{flex-direction:column}.topbar{height:62px}.display-controls [data-density-toggle]{display:none}.auth-tools{right:14px;top:14px}.page-head h1{font-size:23px}.actions{width:100%}.actions .btn{flex:1}.toolbar>*{width:100%;flex-basis:100%!important}.toolbar .btn{width:100%}}
`;

const icon=n=>`<i class="fi fi-rr-${n}"></i>`;
export const csrfField=t=>`<input type="hidden" name="_csrf" value="${esc(t)}">`;
export function notice(url,explicit=null){const n=explicit||msg(url);return n?`<div class="notice ${n.type}">${esc(n.text)}</div>`:""}
export function badge(status){return `<span class="badge ${status==="ACTIVE"?"ok":"off"}">${esc(status)}</span>`}

export function authPage({title,subtitle="",content,version="1.1.0"}){
  return `<!doctype html><html data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>${esc(title)} · Student IMS</title><link rel="stylesheet" href="https://cdn-uicons.flaticon.com/3.0.0/uicons-regular-rounded/css/uicons-regular-rounded.css"><link rel="stylesheet" href="/assets/app.css"><script defer src="/assets/app.js"></script></head><body><div class="auth-tools"><button class="control-chip" type="button" data-theme-toggle aria-label="Change theme"><i class="fi fi-rr-computer" data-theme-icon></i><span data-theme-label>System</span></button></div><main class="auth"><section class="auth-card"><div class="brand">${icon("graduation-cap")}<div><strong>Student IMS Next</strong><small>D1 edition · V${esc(version)}</small></div></div><h1>${esc(title)}</h1>${subtitle?`<p class="muted">${esc(subtitle)}</p>`:""}${content}<div class="footer-note">UIcons by Flaticon · Theme preference stays on this device</div></section></main></body></html>`;
}

const NAV=[
  ["dashboard.view","/dashboard","home","Dashboard","dashboard"],
  ["students.view","/students","users-alt","Students","students"],
  ["batches.view","/batches","layers","Batches","batches"],
  ["lecturers.view","/lecturers","chalkboard-user","Lecturers","lecturers"],
  ["subjects.view","/subjects","book-alt","Subjects","subjects"],
  ["groups.view","/groups","users-class","Groups","groups"],
  ["reports.view","/reports","chart-histogram","Reports","reports"],
  ["users.view","/users","user-gear","Users & Permissions","users"],
  ["activity.view","/activity","time-past","Activity","activity"],
  ["settings.view","/settings","settings","Settings","settings"]
];

export function appPage({title,user,settings,active,url,content,actions=""}){
  const org=settings.organization_name||"Student Information System";
  const nav=NAV.filter(([p])=>can(user,p)).map(([,h,i,l,k])=>`<a href="${h}" class="${active===k?"active":""}" title="${esc(l)}">${icon(i)}<span>${esc(l)}</span></a>`).join("");
  const initials=user.full_name.split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase();
  return `<!doctype html><html data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>${esc(title)} · ${esc(org)}</title><link rel="stylesheet" href="https://cdn-uicons.flaticon.com/3.0.0/uicons-regular-rounded/css/uicons-regular-rounded.css"><link rel="stylesheet" href="/assets/app.css"><script defer src="/assets/app.js"></script></head><body><div class="mobile-overlay" data-mobile-overlay></div><div class="app"><aside class="sidebar"><div class="side-brand">${icon("graduation-cap")}<div><strong>${esc(org)}</strong><small>Student IMS Next</small></div></div><div class="sidebar-tools"><button class="icon-btn sidebar-collapse" type="button" data-sidebar-collapse title="Collapse sidebar"><i class="fi fi-rr-angle-double-small-left" data-sidebar-collapse-icon></i></button></div><nav class="nav">${nav}<div class="sep"></div><a href="/profile" class="${active==="profile"?"active":""}" title="My Profile">${icon("user")}<span>My Profile</span></a><a href="/sessions" class="${active==="sessions"?"active":""}" title="Sessions">${icon("devices")}<span>Sessions</span></a></nav></aside><div class="main"><header class="topbar"><div class="topbar-left"><button class="icon-btn mobile-menu" type="button" data-mobile-menu aria-label="Open menu">${icon("menu-burger")}</button><span class="top-title">${esc(title)}</span></div><div class="topbar-right"><div class="display-controls"><button class="control-chip" type="button" data-density-toggle title="Layout density">${icon("apps")}<span data-density-label>Comfortable</span></button><button class="control-chip" type="button" data-theme-toggle title="Theme"><i class="fi fi-rr-computer" data-theme-icon></i><span data-theme-label>System</span></button></div><div class="userchip"><div class="avatar">${esc(initials)}</div><div><strong class="small">${esc(user.full_name)}</strong><div class="small muted">${esc(user.role.replace("_"," "))}</div></div></div></div></header><main class="page"><div class="page-head"><div><h1>${esc(title)}</h1></div><div class="actions">${actions}</div></div>${notice(url)}${content}</main></div></div></body></html>`;
}
