export const nowIso = () => new Date().toISOString();
export const clean = (v = "", max = 5000) => String(v ?? "").trim().slice(0, max);
export const normalizeEmail = (v = "") => String(v ?? "").trim().toLowerCase();
export const intId = v => { const n = Number.parseInt(String(v), 10); return Number.isSafeInteger(n) && n > 0 ? n : null; };
export const validEmail = e => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e) && e.length <= 254;
export function esc(v = "") { return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }
export function validatePassword(p) { const e=[]; if(p.length<8)e.push("Password must be at least 8 characters."); if(p.length>128)e.push("Password is too long."); if(!/[A-Z]/.test(p))e.push("Add an uppercase letter."); if(!/[a-z]/.test(p))e.push("Add a lowercase letter."); if(!/[0-9]/.test(p))e.push("Add a number."); return e; }
export async function readForm(request) { const fd=await request.formData(); const o={}; for(const [k,v] of fd.entries()){ if(k in o)o[k]=Array.isArray(o[k])?[...o[k],v]:[o[k],v]; else o[k]=v; } return o; }
export function redirect(location,status=303,headers={}){ return new Response(null,{status,headers:{location,"cache-control":"no-store",...headers}}); }
export function html(body,status=200,extraHeaders={}) { const h=new Headers({"content-type":"text/html; charset=UTF-8","cache-control":"no-store","x-content-type-options":"nosniff","x-frame-options":"DENY","referrer-policy":"strict-origin-when-cross-origin","permissions-policy":"camera=(), microphone=(), geolocation=()","content-security-policy":"default-src 'self'; style-src 'self' https://cdn-uicons.flaticon.com; font-src 'self' https://cdn-uicons.flaticon.com; img-src 'self' data:; form-action 'self'; frame-ancestors 'none'; base-uri 'self'; object-src 'none'"}); for(const[k,v]of Object.entries(extraHeaders))h.append(k,v); return new Response(body,{status,headers:h}); }
export function text(body,status=200,type="text/plain; charset=UTF-8",headers={}){return new Response(body,{status,headers:{"content-type":type,...headers}})}
export function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=UTF-8","cache-control":"no-store"}})}
export function csvEscape(v){const s=String(v??"");return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
export function csvResponse(rows,filename){const body="\uFEFF"+rows.map(r=>r.map(csvEscape).join(",")).join("\r\n");return new Response(body,{headers:{"content-type":"text/csv; charset=UTF-8","content-disposition":`attachment; filename="${filename}"`,"cache-control":"no-store"}})}
export function parseCsv(input){const rows=[];let row=[],field="",quoted=false;for(let i=0;i<input.length;i++){const c=input[i];if(quoted){if(c==='"'&&input[i+1]==='"'){field+='"';i++;}else if(c==='"')quoted=false;else field+=c;}else{if(c==='"')quoted=true;else if(c===","){row.push(field);field="";}else if(c==="\n"){row.push(field.replace(/\r$/, ""));rows.push(row);row=[];field="";}else field+=c;}}if(field.length||row.length){row.push(field.replace(/\r$/, ""));rows.push(row);}return rows.filter(r=>r.some(v=>String(v).trim()!==""));}
export function msg(url){const m=url.searchParams.get("msg");return m?{text:m,type:url.searchParams.get("type")==="error"?"error":"success"}:null}
